export const Colors = [
    {"name": "Red","hex": "#FF0000"},
    {"name": "Green","hex": "#00FF00"},
    {"name": "Blue","hex": "#0000FF"},
    {"name": "NavyBlue","hex": "#000080"},
    {"name": "Yellow","hex": "#FFFF00"},
    {"name": "Orange","hex": "#FFA500"},
    {"name": "Purple","hex": "#800080"},
    {"name": "Pink","hex": "#FFC0CB"},
    {"name": "Brown","hex": "#A52A2A"},
    {"name": "Gray","hex": "#808080"},
    {"name": "Black","hex": "#000000"},
    {"name": "White","hex": "#FFFFFF"},
    {"name": "Cyan","hex": "#00FFFF"},
    {"name": "Teal","hex": "#008080"},
    {"name": "Lime","hex": "#00FF00"},
    {"name": "Indigo","hex": "#4B0082"},
    {"name": "Violet","hex": "#8F00FF"},
    {"name": "Magenta","hex": "#FF00FF"},
    {"name": "Maroon","hex": "#800000"},
    {"name": "Olive","hex": "#808000"},
    {"name": "Gold","hex": "#FFD700"},
    {"name": "Silver","hex": "#C0C0C0"},
    {"name": "Beige","hex": "#F5F5DC"},
    {"name": "Coral","hex": "#FF7F50"},
    {"name": "Salmon","hex": "#FA8072"},
    {"name": "Turquoise","hex": "#40E0D0"},
    {"name": "SkyBlue","hex": "#87CEEB"},
    {"name": "RoyalBlue","hex": "#4169E1"},
    {"name": "Crimson","hex": "#DC143C"},
    {"name": "Chocolate","hex": "#D2691E"},
    {"name": "Lavender","hex": "#E6E6FA"},
    {"name": "Mint","hex": "#98FF98"},
    {"name": "Ivory","hex": "#FFFFF0"},
    {"name": "Charcoal","hex": "#36454F"}

]